services:
  mana-archive:
    build: .
    container_name: mana-archive
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - APP_VERSION=dev-version
    restart: unless-stopped
